services:
  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'

    env_file:
      .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3001:3001'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  postgres_data: