# Generated by Django 5.1.2 on 2024-10-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FancyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FancyListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.category')),
                ('FancyList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.fancylist')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='lists',
            field=models.ManyToManyField(through='lists.FancyListCategory', to='lists.fancylist'),
        ),
        migrations.CreateModel(
            name='FancyListCategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('FancyListCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.fancylistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('listCategory', models.ManyToManyField(through='lists.FancyListCategoryItem', to='lists.fancylistcategory')),
            ],
        ),
        migrations.AddField(
            model_name='fancylistcategoryitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.item'),
        ),
    ]
