# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_fancylistcategoryitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listCategory',
            field=models.ManyToManyField(through='lists.FancyListCategoryItem', to='lists.FancyListCategory'),
        ),
    ]
